language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo build --verbose --release

  - cargo build --verbose --features iron-handlers
  - cargo build --verbose --features iron-handlers --release

  - cargo test --verbose --features iron-handlers
  - cargo test --verbose --features iron-handlers --release

before_cache:
  rm -rf target/debug/juniper*
  rm -rf target/release/juniper*

after_success: |
  if [ "$TRAVIS_BRANCH" = master -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_RUST_VERSION" = stable ]; then
    set -e

    cargo doc --features iron-handlers

    mkdir -p ~/.ssh
    openssl aes-256-cbc -K $encrypted_7258158212d8_key -iv $encrypted_7258158212d8_iv -in _build/travis-juniper.enc -out ~/.ssh/id_rsa -d
    chmod 600 ~/.ssh/id_rsa

    git clone --branch gh-pages git@github.com:mhallin/juniper deploy_docs
    cd deploy_docs

    git config user.name 'Juniper Documentation Builder'
    git config user.email 'nobody@example.com'

    rm -rf *
    mv ../target/doc/* .

    echo '<meta http-equiv="refresh" content="0; url=juniper/index.html">' > index.html

    git add -A *
    git commit -qm 'Update documentation for Juniper'
    git push -q origin gh-pages
  fi
