language: rust

rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly

script:
    cargo build --verbose
    cargo build --features iron-handlers --verbose

    cargo test --verbose --features iron-handlers
