[package]
name = "juniper"
version = "0.6.2"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "http://mhallin.github.io/juniper"
repository = "https://github.com/mhallin/juniper"
readme = "README.md"
keywords = ["graphql", "server", "iron", "http", "web"]
categories = ["web-programming"]

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"

[features]
default = ["rustc-serialize"]
nightly = []
iron-handlers = ["iron", "rustc-serialize"]
expose-test-schema = []

[dependencies]
rustc-serialize = { version = "^0.3.19", optional = true }
iron = { version = "^0.5.1", optional = true }
serde = { version = "^0.9.1", optional = true }

[dev-dependencies]
iron = "^0.5.1"
router = "^0.5.0"
mount = "^0.3.0"
logger = "^0.3.0"
iron-test = "^0.5.0"
bencher = "^0.1.2"
