[package]
name = "juniper"
version = "0.7.0"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "http://mhallin.github.io/juniper"
repository = "https://docs.rs/juniper"
readme = "README.md"
keywords = ["graphql", "server", "iron", "http", "web"]
categories = ["web-programming"]

[package.metadata.docs.rs]
features = [ "iron-handlers" ]

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"

[[example]]
name = "server"
required-features = ["iron-handlers", "expose-test-schema"]

[features]
nightly = []
iron-handlers = ["iron", "serde_json", "urlencoded"]
expose-test-schema = []

[dependencies]
serde = { version = "^1.0.8" }
serde_derive = {version="^1.0.8" }

iron = { version = "^0.5.1", optional = true }
serde_json = { version = "^1.0.2", optional = true }
urlencoded = { version = "^0.5.0", optional = true }

[dev-dependencies]
iron = "^0.5.1"
router = "^0.5.0"
mount = "^0.3.0"
logger = "^0.3.0"
iron-test = "^0.5.0"
bencher = "^0.1.2"
