[package]
name = "juniper"
version = "0.8.1"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper/0.8.1/juniper/"
repository = "https://github.com/mhallin/juniper"
readme = "README.md"
keywords = ["graphql", "server", "web", "rocket"]
categories = ["web-programming"]

[badges]
travis-ci = { repository = "mhallin/juniper" }
appveyor = { repository = "mhallin/juniper" }

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"

[features]
nightly = []
expose-test-schema = []

[dependencies]
serde = { version = "^1.0.8" }
serde_derive = {version="^1.0.8" }
serde_json = { version="^1.0.2", optional = true }

[dev-dependencies]
bencher = "^0.1.2"
serde_json = { version = "^1.0.2" }