[package]
name = "juniper"
version = "0.14.2"
authors = [
    "Magnus Hallin <mhallin@fastmail.com>",
    "Christoph Herzog <chris@theduke.at>",
    "Christian Legnitto <christian@legnitto.com>",
]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper"
repository = "https://github.com/graphql-rust/juniper"
readme = "../README.md"
keywords = ["graphql", "server", "web", "rocket"]
categories = ["web-programming"]
edition = "2018"

[badges]
travis-ci = { repository = "graphql-rust/juniper" }

[features]
default = [
    "bson",
    "chrono",
    "schema-language",
    "url",
    "uuid",
]
expose-test-schema = ["serde_json"]
graphql-parser-integration = ["graphql-parser"]
scalar-naivetime = []
schema-language = ["graphql-parser-integration"]

[dependencies]
juniper_codegen = { version = "0.14.2", path = "../juniper_codegen"  }

bson = { version = "1.0", optional = true }
chrono = { version = "0.4", optional = true }
fnv = "1.0.3"
futures = "0.3.1"
futures-enum = "0.1.12"
graphql-parser = { version = "0.3", optional = true }
indexmap = { version = "1.0", features = ["serde-1"] }
serde = { version = "1.0.8", features = ["derive"] }
serde_json = { version = "1.0.2", optional = true }
static_assertions = "1.1"
url = { version = "2.0", optional = true }
uuid = { version = "0.8", optional = true }

[dev-dependencies]
bencher = "0.1.2"
serde_json = { version = "1.0.2" }
tokio = { version = "0.2", features = ["macros", "rt-core", "time"] }

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"
