[package]
name = "juniper_codegen"
version = "0.8.1"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
description = "Internal custom derive trait for Juniper GraphQL"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper"
repository = "https://github.com/graphql-rust/juniper"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[badges]
travis-ci = { repository = "graphql-rust/juniper" }
appveyor = { repository = "graphql-rust/juniper" }
